### ISSUE TITLE
Præsentation af uddannelse til nye elever

### ISSUE THREAD

**Issue by SanderSalamander** [WeWebSKOLE/ProjektAfrika#34]
Uddannelsen skal præsenteres (Den skal se sej ud) :)))))

**Comment by MathiasMogensen** [comment]
Lidt noter:

Sort humor
Meget går ud på at sidde og kigge ind i en skærm
Ansvar for egen læring - der skal søges på nettet!
Ingen lektier (Kodning hjemme anbefales dog stærkt)
